### ISSUE TITLE
0 != 0

### ISSUE THREAD

**Issue by blaggacao** [acsone/odoo-bedrock#1]
https://github.com/acsone/odoo-bedrock/blob/49ee1a8aabac16c26ca5898d7f77de0227a38d57/bin/entrypoint.sh#L20-L23

I fear this might fail on network volumes which have a lifecycle external to the Odoo deployment. Or if you run a user-namespaced (and mapped) `dockerd`.

I think there needs to be a better way to persistence lifecycle management.

In any case, for a minimal bedrock, stepping down from `root` is an anti-pattern... :wink:

**Comment by sbidoul** [comment]
There is no know negative side effect to this `chown`. I suggest to reopen when an actual problematic use case surfaces.

Using USER in a base image is probably an anti pattern. I don't see how running gosu at the end of the entry point when the command is `odoo` is a problem. On the contrary, I think it's a safe default behaviour (that can be overridden with another CMD if needed).

**Comment by blaggacao** [comment]
> Using USER in a base image is probably an anti pattern

Why? I've come to acknowledge the contrary. Could you explain?

**Comment by sbidoul** [comment]
anti-pattern might be a strong word. Let's say more cumbersome for people creating derived images. 

What we do here with gosu is also safe by default. And running the entrypoints as root is a feature not a risk IMO (entrypoints are trusted code, not interacting with the user).

**Comment by blaggacao** [comment]
> What we do here with gosu is also safe by default. And running the entrypoints as root is a feature not a risk IMO (entrypoints are trusted code, not interacting with the user).

Ok, I might temper my words, but do you really rely on this extra layer?

I think the true and truthful answer is: "No." So why should something be there, that's not needed in the first place?

**Comment by sbidoul** [comment]
I you show me another method to run the entrypoints as root and *then* step down to run the cmd, I'll reconsider

**Comment by blaggacao** [comment]
May I express a daring assumption about your context?

- The only reason you want root privileges (by default!) is because you need to manipulate permissions on some host volume.
- Currently docker does no user mapping by default (though: you can configure it on `dockerd`)

To be clear, conceptually host is host, and if the host set's permissions on any volume to `root`, we should assume this has been on purpose. So if a host volume says root, it's meant to be root.

Enter misunderstandings:
- The SysAdmin of the host might not have been carefull
- The host volume might not have existed and docker itself is just negligent (it doe not create as root, it creats as docker user)

Now, what we might want in the case of misunderstandings is a helper image (aka `sidekick` or `sidecar`) which should be named (I'm exaggerating) `fix-carless-host-sysadmin:latest`.

This image should be run as init container to the actual production image, ok, with root, and everything. But it's marked clearly as what it is "a fix for careless sysadmins".

It really hurts to bake that into a serious and responible production (base) image.

Note: when using `StorageClasses`, k8s is smart enough to set the security context as per which the host volume will be created https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod (note fsGroup)
