### ISSUE TITLE
Remove confd

### ISSUE THREAD

**Issue by hparfr** [acsone/odoo-bedrock#17]
Last release of confd is from 2018 !

Because the goal of this project is to be minimal and not assume too much project structure, why not just remove confd ?

1) it can be added back in another upper image level to not break too many things.
2) or it can be replaced in this repo just by some basic unix tools (in my use case, it's source is environment variables)

(I had issues while building this image from aarch64 platform)

**Comment by sbidoul** [comment]
I'm happy to declare that `confd` is not part of the public interface of this image (see #20).

However, the generation of odoo.cfg from environment variables must be preserved, together with the same default values.
