### ISSUE TITLE
patch conf for live atomic config updates rather than another conf layer.

### ISSUE THREAD

**Issue by blaggacao** [acsone/odoo-bedrock#2]
Patch `conf` odoo where it reads config directly from environment? (/cc @guewen)

This would enable atomic config updates against a running cluster without a server restart (for certain options).

This would be cheerily bedrock :wink:

**Comment by sbidoul** [comment]
This is not supported by Odoo. Too dangerous.

**Comment by blaggacao** [comment]
Fair argument!
