### ISSUE TITLE
ENV vs ConfigMaps

### ISSUE THREAD

**Issue by blaggacao** [acsone/odoo-bedrock#3]
Recently, the container ecosystem has evolved towards the use of `ConfigMaps`. 

They make the old environment variable hack (yes it was a hack) somewhat obsolete.

`ConfigMaps` might be the semantically optimal place for configuration data.

Wouldn't this bedrock attempt be a chance to do away with the ENV "anti-pattern"?

**Comment by sbidoul** [comment]
We use confd which supports many more options than env vars.

**Comment by blaggacao** [comment]
> We use confd which supports many more options than env vars.
confd was invented in the time there was no `ConfigMap` semantics.

The proposal consists in neither using ENV nor confd, but the official configuration API (aka. `ConfigMaps`).

Is this really ready for closure?

**Comment by blaggacao** [comment]
Conceptually, "Pre-Assembly" should not be the task of a functional artifact (aka Image). It's only a hack/workaround.

**Comment by sbidoul** [comment]
Is it correct the ConfigMap would need a key with the whole odoo config file as a value? That sounds cumbersome to me.

**Comment by blaggacao** [comment]
Depends on the implementation, k8s is very very very flexible and allows for atomic live updates. It's pure mix and match (and you got it inventorized for free as a `ConfigMap` resource)

For plain docker, I guess it's just one file (but docker is converging towards k8s as it stands)

**Comment by blaggacao** [comment]
I admit, there is no easy solution, but maybe the best thing to do would push Odoo towards adopting better config interface over time?

I think the config hierarchy and their respective living place should be:

Defaults : Odoo Server
Conf-File : Odoo Operator (either human or machine) - but independent lifecycle from the server.
ENV / CLI flags : AD hoc overrides for one-offs or local environment constants.

**Comment by blaggacao** [comment]
Using ENV further up the latter is relatively verbose, actually.

**Comment by blaggacao** [comment]
I feel: lack of inventorization renders ENV a no go for production deployments...

**Comment by sbidoul** [comment]
Yet 12 factors is still a thing right? And it recommends envelope vars. And ConfigMaps can easily be exposed to pods as env vars. So I think confd is a good compromise given the way Odoo configures itself today.

**Comment by blaggacao** [comment]
The think is it is an API wrapper. Thinks like this: https://github.com/xoe-labs/odoo-operator/blob/master/config/samples/overlays/odoocluster/patch_odoocluster.yaml become impossible.

And how do we expose or transport custom config options without needing an API change? It seems very unhandy to me, also most people are familiar with odoo's config file format...

I don't know the ultimate answer, yet, but I know we need a better one.

**Comment by sbidoul** [comment]
I think I'll stick with env vars for now and these Odoo versions.

See also #7

**Comment by blaggacao** [comment]
I'm not really sure about this, problem is really that configs are not inventorized. And this env thing is not compatible with current Odoo-Operator approach (which for the reasons of inventorization might not change).

Using env I'd need to create another wrapper around this wrapper to function properly, and it will just result in chaotic UX, so I probably won't do that.

I would be great, indeed, if this bedrock could be generic enough to support that use case, too...

**Comment by sbidoul** [comment]
If you want to put the config in a ConfigMap you can, and expose it to the container as env vars: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-container-environment-variables

**Comment by blaggacao** [comment]
@sbidoul This doesn't seem really well thought trough: The link you mention changes completely the odoo config API. That's not the use case, I exposed.

**Comment by sbidoul** [comment]
Does it?

**Comment by blaggacao** [comment]
> Does it?

Yes:
```
   data:
     SPECIAL_LEVEL: very
     SPECIAL_TYPE: charm
```

**Comment by sbidoul** [comment]
You have two options if you want ConfigMaps:
- set ONE env var: OPENERP_SERVER=/some/data/volume/odoo.cfg where odoo.cfg comes from the ConfigMap
- create a ConfigMap containing the env var definitions as defined in the confd template and expose it to the pod as env vars using the link I pointed to above

**Comment by blaggacao** [comment]
Ok that would work, but it seems like we end up with 15 different variants on how to configure a "base" container. Truthfully, is that what we want? For a _base_ container?

Can't we just try a little harder on an effort of dis-intermediatation?
Why: It helps consolidating knowledge and best practices.

@sbidoul Maybe you can expose any strict requirement for wrapping everything into `confd` that could not be solved more elegantly?

Note: If the "common denominator" stance of this repo is to be withdrawn, I'd just desist and move on, but I think this problem needs a sleak common-denominator solution.

**Comment by sbidoul** [comment]
Well that discussion was indeed interesting and I did learn something in the process.

I showed you both approaches (env vars and rc file from config map) are equally well supported by the current code. I'll explain it in the README too.

Since I'm running out of ideas, I'll close and I'll be happy to review a PR with a better approach.

**Comment by blaggacao** [comment]
> Since I'm running out of ideas, I'll close and I'll be happy to review a PR with a better approach.

Fair enough. Give me some time, I'l machine this a little bit around, maybe I can come up with a PR. (I hope so, cause I don't like this variadic approach at this basic level)

**Comment by blaggacao** [comment]
Based on Odoo accepting the PR, I think I have a good idea.

**Why should they?**
- many config options have very different scopes and lifecycles, unbundling is almost imperative.

**For local dev:**

```
.cfg  # This is managed by you
.cfg-default  # This is managed by your company
```

While working on a local dev, fine tune options (and exempt from vcs):
```bash
echo ".cfg" > .gitignore
nano .cfg
```

**For deployment:**

- Reuses `.cfg-default`
- `.cfg` is administered (either, or):

  - As a `ConfigMap`
  - As a (single) multi-line `ENV` variable

**Result:**

- We all save on one obsolete init-layer (odoo reads config folders)
- No config API wrapper (everyone is familiar with `ini` style configs)
- Clear abstract semantics: You craft `.cfg` according to your current environment.
- Better inventorization of single source of truth: `.cfg` (file-type artifact, version controlling, etc...)

I think that is the single most elegant solution and fits everyone's use case perfectly. In this case, agreeing to push a single and precise 7 line patch seems a lot more warranted than 500 lines of workaround.
