### ISSUE TITLE
A better way of host UID/GID impersonation

### ISSUE THREAD

**Issue by blaggacao** [acsone/odoo-bedrock#4]
`LOCAL_USER_ID` transcends a host concept into the container artifact (which should probably not care about the host).

Fortunately there is a better pattern to solve the impersonation problem in local dev: https://github.com/xoe-labs/dockery-odoo-scaffold/blob/ef8db96a3d422afc068bc43d6efead8aa3cff5b6/docker-compose.override.yml#L71

**Comment by blaggacao** [comment]
It is a one time host level command: `echo "export COMPOSE_IMPERSONATION='$(id -u):$(id -g)'" > ~/.bashrc && source ~/.bashrc`, see https://xoe-labs.github.io/dockery-odoo/

**Comment by sbidoul** [comment]
The concept is very similar, and I find it useful to have the entrypoints doing stuff as root before stepping down to an unpriviledged user (which AFAICT docker run --user does not allow).

**Comment by blaggacao** [comment]
> which AFAICT docker run --user does not allow

It does.
And executing as root (even though for a very short period is a recognized anti-pattern.

**Comment by blaggacao** [comment]
@sbidoul tempered the wording :wink:
