### ISSUE TITLE
Scope of Makefile vs docker-compose UX

### ISSUE THREAD

**Issue by blaggacao** [acsone/odoo-bedrock#5]
I really like the idea of a Makefile for all things repo-automation concerned outside of the in-container scope itself.

However, I think there needs to be a guideline decision made as to where `docker-compose` should prevail and where is `make`'s realm. Or should we just let `docker-compose` be overtaken by `make` also in local dev? What do we need `docker-compose` for? As a **declarative** dev-environment yaml file?

**Comment by sbidoul** [comment]
The makefile is only here to build and publish the image in travis. Nothing to do with docker-compose.

**Comment by blaggacao** [comment]
> The makefile is only here to build and publish the image in travis. Nothing to do with docker-compose.

Sorry, but this seems to be a down-turning response to an open question, nobody has really answered, yet. If this is to be the bedrock, then some conceptualization would be rather a win then a nuisance.

**Comment by sbidoul** [comment]
It's not down turning. An issue in this project is not a place for such a discussion. I don't see how docker-compose would make sense for the narrow use case of building the image in travis.

**Comment by blaggacao** [comment]
You're absolutley right. What my motivation and intention for this is:
- As a odoo-bedrock, the real value of this is mind-share.
- That is: mind-share through shared conceptualizations.

I can answer my proposed question for myself in private, but if we find a common answer, the value of odoo-bedrock, all of a sudden, skyrockets.

But if you don't think issues are the appropriate point for such, I can understand and respect that and will withhold in future. Maybe twitter is a better place... (althoug it's very ephimeral)
