### ISSUE TITLE
Make use of DEFAULT configparser feature

### ISSUE THREAD

**Issue by blaggacao** [acsone/odoo-bedrock#6]
To set sane defaults and reduce the need for an ENV wall or a very extensive config API, we could make use of the [DEFAULT] section feautre of configparser, see [in action](https://github.com/xoe-labs/odoo-operator/blob/1be88b67d4ded5c4a0aea6e26b711241f0d09f89/pkg/controller/odoocluster/odoocluster_configs.go#L34-L50) and [in theory](https://stackoverflow.com/a/124785).

**Comment by sbidoul** [comment]
There are defaults in the confd template.

**Comment by blaggacao** [comment]
> There are defaults in the confd template.

I think my other Issue was misunderstood: confd is not the official configuration API (its a hack of the past).

Is this really closeable?
